program:	main.o funkcje.o
		g++ -o program main.o funkcje.o -Wall -pedantic -std=c++11
funkcje.o:	funkcje.cpp
		g++ -o funkcje.o -c funkcje.cpp -Wall -pedantic -std=c++11
main.o:	main.cpp 
		g++ -o main.o -c main.cpp -Wall -pedantic -std=c++11
